<?php

/**
 * Implements hook_theme().
 */
function saibher_components_theme($existing, $type, $theme, $path) {
  return [
    'hero_banner_one' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
    'hero_banner_two' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
    'three_cols_feature_one' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
    'two_cols_section_one' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function saibher_components_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'saibher_components/global'; 
}
