progress:
  '#changed': 1681526849
  '#changed_by': '1'
  '#completed_items': 51
  '#items':
    install_and_enable_seo_checklist_module:
      '#completed': 1681485603
      '#uid': '1'
    install_and_enable_coffee_module:
      '#completed': 1681485609
      '#uid': '1'
    configure_coffee_module:
      '#completed': 1681485609
      '#uid': '1'
    install_and_enable_admin_toolbar_module:
      '#completed': 1681485603
      '#uid': '1'
    install_composer_command_line_tool:
      '#completed': 1681485603
      '#uid': '1'
    install_drush_command_line_tool:
      '#completed': 1681485603
      '#uid': '1'
    show_cli_commands:
      '#completed': 1681485603
      '#uid': '1'
    enable_clean_urls:
      '#completed': 1681521881
      '#uid': '1'
    install_and_enable_redirect_module:
      '#completed': 1681485804
      '#uid': '1'
    install_and_enable_pathauto_module:
      '#completed': 1681485804
      '#uid': '1'
    configure_pathauto_module:
      '#completed': 1681521865
      '#uid': '1'
    create_pathauto_patterns:
      '#completed': 1681521865
      '#uid': '1'
    install_and_enable_file_field_paths_module:
      '#completed': 1681485804
      '#uid': '1'
    configure_file_field_paths_module:
      '#completed': 1681485804
      '#uid': '1'
    install_and_enable_metatag_module:
      '#completed': 1681485998
      '#uid': '1'
    install_and_enable_schema_metatag:
      '#completed': 1681485998
      '#uid': '1'
    set_metatags_for_your_site:
      '#completed': 1681522870
      '#uid': '1'
    install_and_enable_alternate_hreflang_module:
      '#completed': 1681485998
      '#uid': '1'
    install_and_enable_xml_sitemap_module:
      '#completed': 1681486501
      '#uid': '1'
    configure_xml_sitemap_module:
      '#completed': 1681523272
      '#uid': '1'
    install_and_enable_robotstxt_module:
      '#completed': 1681486501
      '#uid': '1'
    add_xml_sitemap_to_your_robotstxt_file:
      '#completed': 1681526849
      '#uid': '1'
    set_up_cron:
      '#completed': 1681526849
      '#uid': '1'
    google_accounts_sign_ups:
      '#completed': 1681526849
      '#uid': '1'
    install_and_enable_google_tag_manager_module:
      '#completed': 1681486501
      '#uid': '1'
    configure_google_tag_manager_module:
      '#completed': 1681526849
      '#uid': '1'
    submit_xml_sitemap_to_google:
      '#completed': 1681526849
      '#uid': '1'
    get_a_microsoft_account:
      '#completed': 1681526849
      '#uid': '1'
    authenticate_with_bing:
      '#completed': 1681526849
      '#uid': '1'
    submit_xml_sitemap_to_bing:
      '#completed': 1681526849
      '#uid': '1'
    install_and_enable_easy_breadcrumbs_module:
      '#completed': 1681486689
      '#uid': '1'
    install_and_enable_d8_editor_advanced_link_module:
      '#completed': 1681486689
      '#uid': '1'
    install_and_enable_sitemap_module:
      '#completed': 1681485603
      '#uid': '1'
    configure_sitemap_module:
      '#completed': 1681485603
      '#uid': '1'
    install_and_enable_search_404_module:
      '#completed': 1681486751
      '#uid': '1'
    install_and_enable_yoast_seo_module:
      '#completed': 1681487071
      '#uid': '1'
    install_and_enable_diff_module:
      '#completed': 1681487071
      '#uid': '1'
    configure_the_diff_module:
      '#completed': 1681487381
      '#uid': '1'
    install_and_enable_scheduler_module:
      '#completed': 1681487071
      '#uid': '1'
    install_and_enable_security_review_module:
      '#completed': 1681487381
      '#uid': '1'
    install_and_enable_honeypot_module:
      '#completed': 1681487381
      '#uid': '1'
    install_and_enable_advanced_css_js_aggregation_module:
      '#completed': 1681487381
      '#uid': '1'
    configure_advanced_cssjs_aggregation_module:
      '#completed': 1681487381
      '#uid': '1'
    secure_your_website_with_https:
      '#completed': 1681487452
      '#uid': '1'
    adjust_performance_admin_settings:
      '#completed': 1681487452
      '#uid': '1'
    configure_image_styles:
      '#completed': 1681487452
      '#uid': '1'
    set_up_a_cdn_cloudflare_etc:
      '#completed': 1681487452
      '#uid': '1'
    move_to_fast_hosting:
      '#completed': 1681487452
      '#uid': '1'
    make_sure_website_is_responsive:
      '#completed': 1681487508
      '#uid': '1'
    install_and_enable_amp_module_theme_and_php_library_using_composer:
      '#completed': 1681487508
      '#uid': '1'
    install_and_enable_share_buttons_by_addtoany:
      '#completed': 1681485603
      '#uid': '1'
