_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  checklistapi: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  content_entity_example: 0
  contextual: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  entity_reference_revisions: 0
  examples: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  hreflang: 0
  image: 0
  language: 0
  layout_builder: 0
  layout_builder_styles: 0
  layout_custom_section_classes: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_app_links: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_extended_perms: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_google_cse: 0
  metatag_google_plus: 0
  metatag_hreflang: 0
  metatag_routes: 0
  metatag_views: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  redirect: 0
  redirect_404: 0
  robotstxt: 0
  saibher_components: 0
  saibher_core: 0
  saibher_password_manager: 0
  saibher_prompt_generator: 0
  saibher_tracking: 0
  scheduler: 0
  schema_metatag: 0
  search: 0
  search404: 0
  security_review: 0
  seo_checklist: 0
  shortcut: 0
  simplenews: 0
  sitemap: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  xmlsitemap_engines: 0
  yoast_seo: 0
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  saibher: 0
profile: standard
