entity_type_groups:
  node:
    article:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
    faqs:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
    page:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
    proyects:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
    servicio:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
  path_alias:
    path_alias:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
  redirect:
    redirect:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
  taxonomy_term:
    article_category:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
    categoria_faq:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
    tags:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
    tecnologias_o_lenguajes_de_progr:
      app_links: app_links
      favicons: favicons
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
      facebook: facebook
      google_plus: google_plus
      hreflang: hreflang
      google_cse: google_cse
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
  metatag_maxlength_dcterms_title: null
  metatag_maxlength_dcterms_description: null
  metatag_maxlength_google_plus_description: null
  metatag_maxlength_google_plus_name: null
tag_scroll_max_height: ''
