_core:
  default_config_hash: us91yAZ2i-PBRNGxbudkfTDsiVfCpbLCNPOGmO78NJ4
langcode: es
hash_expiration: 86400
newsletter:
  issue_tokens: false
  format: plain
  priority: 0
  receipt: true
  from_address: developer@saibher.com
  from_name: saibher
subscriber:
  sync_fields: true
subscription:
  skip_verification: true
  tidy_unconfirmed: 7
  confirm_combined_subject: 'Confirma tu suscripción a saibher'
  confirm_combined_body: "Hemos recibido tu solicitud para suscribir a [simplenews-subscriber:mail] a [site:url]. Para confirmar su solicitud por favor dar click en el siguiente enlace.\r\n\r\n[simplenews-subscriber:combined-url]"
  confirm_combined_body_unchanged: 'We have received a request to subscribe [simplenews-subscriber:mail] at [site:url]. No confirmation necessary because you are already subscribed.'
  confirm_subscribe_page: /blog
  confirm_unsubscribe_page: /blog
  validate_subject: 'Manage your subscriptions at [site:name]'
  validate_body: "We have received a request to manage your subscriptions for [simplenews-subscriber:mail] at [site:url]. To proceed please use the link below.\r\n\r\n[simplenews-subscriber:manage-url]"
mail:
  use_cron: true
  textalt: false
  throttle: -1
  spool_progress_expiration: 3600
  spool_expire: 0
  debug: false
  source_cache: null
