_core:
  default_config_hash: xu0yG13sSQJcXrOJJqsn44W_hUWAIFHVlphrzxT2ycU
langcode: es
page_title: 'Mapa del sitio'
message:
  value: ''
  format: plain_text
plugins:
  'vocabulary:article_category':
    enabled: true
    weight: 0
    settings:
      title: 'categoría de artículo'
      show_description: false
      show_count: false
      display_unpublished: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
    id: 'vocabulary:article_category'
    provider: sitemap
  'vocabulary:tecnologias_o_lenguajes_de_progr':
    enabled: true
    weight: 0
    settings:
      title: 'Tecnologías o lenguajes de programacion'
      show_description: false
      show_count: false
      display_unpublished: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
    id: 'vocabulary:tecnologias_o_lenguajes_de_progr'
    provider: sitemap
  frontpage:
    enabled: false
  'menu:main':
    enabled: true
    weight: 0
    settings:
      title: 'Navegación principal'
      show_disabled: false
    id: 'menu:main'
    provider: sitemap
include_css: true
