_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: es
uuid: 8c2ef40a-45d3-48ce-b442-05fc2da495f2
name: saibher
mail: developer@saibher.com
slogan: ''
page:
  403: ''
  404: /search404
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
